/* Source and licensing information for the line(s) below can be found at https://projektballast.dk/sites/all/modules/tabvn/flexslider_format/js/jquery.flexslider.js. */
(function(e){e.flexslider=function(n,d){var t=e(n),i=e.extend({},e.flexslider.defaults,d),a=i.namespace,u=('ontouchstart' in window)||window.DocumentTouch&&document instanceof DocumentTouch,p=(u)?'touchend':'click',l=i.direction==='vertical',r=i.reverse,s=(i.itemWidth>0),c=i.animation==='fade',f=i.asNavFor!=='',o={};e.data(n,'flexslider',t);o={init:function(){t.animating=!1;t.currentSlide=i.startAt;t.animatingTo=t.currentSlide;t.atEnd=(t.currentSlide===0||t.currentSlide===t.last);t.containerSelector=i.selector.substr(0,i.selector.search(' '));t.slides=e(i.selector,t);t.container=e(t.containerSelector,t);t.count=t.slides.length;t.syncExists=e(i.sync).length>0;if(i.animation==='slide')i.animation='swing';t.prop=(l)?'top':'marginLeft';t.args={};t.manualPause=!1;t.transitions=!i.video&&!c&&i.useCSS&&(function(){var n=document.createElement('div'),e=['perspectiveProperty','WebkitPerspective','MozPerspective','OPerspective','msPerspective'];for(var i in e){if(n.style[e[i]]!==undefined){t.pfx=e[i].replace('Perspective','').toLowerCase();t.prop='-'+t.pfx+'-transform';return!0}};return!1}());if(i.controlsContainer!=='')t.controlsContainer=e(i.controlsContainer).length>0&&e(i.controlsContainer);if(i.manualControls!=='')t.manualControls=e(i.manualControls).length>0&&e(i.manualControls);if(i.randomize){t.slides.sort(function(){return(Math.round(Math.random())-0.5)});t.container.empty().append(t.slides)};t.doMath();if(f)o.asNav.setup();t.setup('init');if(i.controlNav)o.controlNav.setup();if(i.directionNav)o.directionNav.setup();if(i.keyboard&&(e(t.containerSelector).length===1||i.multipleKeyboard)){e(document).bind('keyup',function(e){var n=e.keyCode;if(!t.animating&&(n===39||n===37)){var a=(n===39)?t.getTarget('next'):(n===37)?t.getTarget('prev'):!1;t.flexAnimate(a,i.pauseOnAction)}})};if(i.mousewheel){t.bind('mousewheel',function(e,n,a,o){e.preventDefault();var s=(n<0)?t.getTarget('next'):t.getTarget('prev');t.flexAnimate(s,i.pauseOnAction)})};if(i.pausePlay)o.pausePlay.setup();if(i.slideshow){if(i.pauseOnHover){t.hover(function(){if(!t.manualPlay&&!t.manualPause)t.pause()},function(){if(!t.manualPause&&!t.manualPlay)t.play()})}(i.initDelay>0)?setTimeout(t.play,i.initDelay):t.play()};if(u&&i.touch)o.touch();if(!c||(c&&i.smoothHeight))e(window).bind('resize focus',o.resize);setTimeout(function(){i.start(t)},200)},asNav:{setup:function(){t.asNav=!0;t.animatingTo=Math.floor(t.currentSlide/t.move);t.currentItem=t.currentSlide;t.slides.removeClass(a+'active-slide').eq(t.currentItem).addClass(a+'active-slide');t.slides.click(function(n){n.preventDefault();var a=e(this),o=a.index();if(!e(i.asNavFor).data('flexslider').animating&&!a.hasClass('active')){t.direction=(t.currentItem<o)?'next':'prev';t.flexAnimate(o,i.pauseOnAction,!1,!0,!0)}})}},controlNav:{setup:function(){if(!t.manualControls){o.controlNav.setupPaging()}
else{o.controlNav.setupManual()}},setupPaging:function(){var l=(i.controlNav==='thumbnails')?'control-thumbs':'control-paging',s=1,r;t.controlNavScaffold=e('<ol class="'+a+'control-nav '+a+l+'"></ol>');if(t.pagingCount>1){for(var n=0;n<t.pagingCount;n++){r=(i.controlNav==='thumbnails')?'<img src="'+t.slides.eq(n).attr('data-thumb')+'"/>':'<a>'+s+'</a>';t.controlNavScaffold.append('<li>'+r+'</li>');s++}}(t.controlsContainer)?e(t.controlsContainer).append(t.controlNavScaffold):t.append(t.controlNavScaffold);o.controlNav.set();o.controlNav.active();t.controlNavScaffold.delegate('a, img',p,function(n){n.preventDefault();var o=e(this),s=t.controlNav.index(o);if(!o.hasClass(a+'active')){t.direction=(s>t.currentSlide)?'next':'prev';t.flexAnimate(s,i.pauseOnAction)}});if(u){t.controlNavScaffold.delegate('a','click touchstart',function(e){e.preventDefault()})}},setupManual:function(){t.controlNav=t.manualControls;o.controlNav.active();t.controlNav.live(p,function(n){n.preventDefault();var o=e(this),s=t.controlNav.index(o);if(!o.hasClass(a+'active')){(s>t.currentSlide)?t.direction='next':t.direction='prev';t.flexAnimate(s,i.pauseOnAction)}});if(u){t.controlNav.live('click touchstart',function(e){e.preventDefault()})}},set:function(){var n=(i.controlNav==='thumbnails')?'img':'a';t.controlNav=e('.'+a+'control-nav li '+n,(t.controlsContainer)?t.controlsContainer:t)},active:function(){t.controlNav.removeClass(a+'active').eq(t.animatingTo).addClass(a+'active')},update:function(i,n){if(t.pagingCount>1&&i==='add'){t.controlNavScaffold.append(e('<li><a>'+t.count+'</a></li>'))}
else if(t.pagingCount===1){t.controlNavScaffold.find('li').remove()}
else{t.controlNav.eq(n).closest('li').remove()};o.controlNav.set();(t.pagingCount>1&&t.pagingCount!==t.controlNav.length)?t.update(n,i):o.controlNav.active()}},directionNav:{setup:function(){var n=e('<ul class="'+a+'direction-nav"><li><a class="'+a+'prev" href="#">'+i.prevText+'</a></li><li><a class="'+a+'next" href="#">'+i.nextText+'</a></li></ul>');if(t.controlsContainer){e(t.controlsContainer).append(n);t.directionNav=e('.'+a+'direction-nav li a',t.controlsContainer)}
else{t.append(n);t.directionNav=e('.'+a+'direction-nav li a',t)};o.directionNav.update();t.directionNav.bind(p,function(n){n.preventDefault();var o=(e(this).hasClass(a+'next'))?t.getTarget('next'):t.getTarget('prev');t.flexAnimate(o,i.pauseOnAction)});if(u){t.directionNav.bind('click touchstart',function(e){e.preventDefault()})}},update:function(){var e=a+'disabled';if(t.pagingCount===1){t.directionNav.addClass(e)}
else if(!i.animationLoop){if(t.animatingTo===0){t.directionNav.removeClass(e).filter('.'+a+'prev').addClass(e)}
else if(t.animatingTo===t.last){t.directionNav.removeClass(e).filter('.'+a+'next').addClass(e)}
else{t.directionNav.removeClass(e)}}
else{t.directionNav.removeClass(e)}}},pausePlay:{setup:function(){var n=e('<div class="'+a+'pauseplay"><a></a></div>');if(t.controlsContainer){t.controlsContainer.append(n);t.pausePlay=e('.'+a+'pauseplay a',t.controlsContainer)}
else{t.append(n);t.pausePlay=e('.'+a+'pauseplay a',t)};o.pausePlay.update((i.slideshow)?a+'pause':a+'play');t.pausePlay.bind(p,function(i){i.preventDefault();if(e(this).hasClass(a+'pause')){t.manualPause=!0;t.manualPlay=!1;t.pause()}
else{t.manualPause=!1;t.manualPlay=!0;t.play()}});if(u){t.pausePlay.bind('click touchstart',function(e){e.preventDefault()})}},update:function(e){(e==='play')?t.pausePlay.removeClass(a+'pause').addClass(a+'play').text(i.playText):t.pausePlay.removeClass(a+'play').addClass(a+'pause').text(i.pauseText)}},touch:function(){var o,d,u,a,e,f,p=!1;n.addEventListener('touchstart',g,!1);function g(e){if(t.animating){e.preventDefault()}
else if(e.touches.length===1){t.pause();a=(l)?t.h:t.w;f=Number(new Date());u=(s&&r&&t.animatingTo===t.last)?0:(s&&r)?t.limit-(((t.itemW+i.itemMargin)*t.move)*t.animatingTo):(s&&t.currentSlide===t.last)?t.limit:(s)?((t.itemW+i.itemMargin)*t.move)*t.currentSlide:(r)?(t.last-t.currentSlide+t.cloneOffset)*a:(t.currentSlide+t.cloneOffset)*a;o=(l)?e.touches[0].pageY:e.touches[0].pageX;d=(l)?e.touches[0].pageX:e.touches[0].pageY;n.addEventListener('touchmove',m,!1);n.addEventListener('touchend',v,!1)}};function m(n){e=(l)?o-n.touches[0].pageY:o-n.touches[0].pageX;p=(l)?(Math.abs(e)<Math.abs(n.touches[0].pageX-d)):(Math.abs(e)<Math.abs(n.touches[0].pageY-d));if(!p||Number(new Date())-f>500){n.preventDefault();if(!c&&t.transitions){if(!i.animationLoop){e=e/((t.currentSlide===0&&e<0||t.currentSlide===t.last&&e>0)?(Math.abs(e)/a+2):1)};t.setProps(u+e,'setTouch')}}};function v(s){n.removeEventListener('touchmove',m,!1);if(t.animatingTo===t.currentSlide&&!p&&!(e===null)){var l=(r)?-e:e,g=(l>0)?t.getTarget('next'):t.getTarget('prev');if(t.canAdvance(g)&&(Number(new Date())-f<550&&Math.abs(l)>50||Math.abs(l)>a/2)){t.flexAnimate(g,i.pauseOnAction)}
else{if(!c)t.flexAnimate(t.currentSlide,i.pauseOnAction,!0)}};n.removeEventListener('touchend',v,!1);o=null;d=null;e=null;u=null}},resize:function(){if(!t.animating&&t.is(':visible')){if(!s)t.doMath();if(c){o.smoothHeight()}
else if(s){t.slides.width(t.computedW);t.update(t.pagingCount);t.setProps()}
else if(l){t.viewport.height(t.h);t.setProps(t.h,'setTotal')}
else{if(i.smoothHeight)o.smoothHeight();t.newSlides.width(t.computedW);t.setProps(t.computedW,'setTotal')}}},smoothHeight:function(e){if(!l||c){var i=(c)?t:t.viewport;(e)?i.animate({'height':t.slides.eq(t.animatingTo).height()},e):i.height(t.slides.eq(t.animatingTo).height())}},sync:function(n){var a=e(i.sync).data('flexslider'),o=t.animatingTo;switch(n){case'animate':a.flexAnimate(o,i.pauseOnAction,!1,!0);break;case'play':if(!a.playing&&!a.asNav){a.play()};break;case'pause':a.pause();break}}};t.flexAnimate=function(n,d,v,x,g){if(f&&t.pagingCount===1)t.direction=(t.currentItem<n)?'next':'prev';if(!t.animating&&(t.canAdvance(n,g)||v)&&t.is(':visible')){if(f&&x){var y=e(i.asNavFor).data('flexslider');t.atEnd=n===0||n===t.count-1;y.flexAnimate(n,!0,!1,!0,g);t.direction=(t.currentItem<n)?'next':'prev';y.direction=t.direction;if(Math.ceil((n+1)/t.visible)-1!==t.currentSlide&&n!==0){t.currentItem=n;t.slides.removeClass(a+'active-slide').eq(n).addClass(a+'active-slide');n=Math.floor(n/t.visible)}
else{t.currentItem=n;t.slides.removeClass(a+'active-slide').eq(n).addClass(a+'active-slide');return!1}};t.animating=!0;t.animatingTo=n;i.before(t);if(d)t.pause();if(t.syncExists&&!g)o.sync('animate');if(i.controlNav)o.controlNav.active();if(!s)t.slides.removeClass(a+'active-slide').eq(n).addClass(a+'active-slide');t.atEnd=n===0||n===t.last;if(i.directionNav)o.directionNav.update();if(n===t.last){i.end(t);if(!i.animationLoop)t.pause()};if(!c){var p=(l)?t.slides.filter(':first').height():t.computedW,S,m,h;if(s){S=(i.itemWidth>t.w)?i.itemMargin*2:i.itemMargin;h=((t.itemW+S)*t.move)*t.animatingTo;m=(h>t.limit&&t.visible!==1)?t.limit:h}
else if(t.currentSlide===0&&n===t.count-1&&i.animationLoop&&t.direction!=='next'){m=(r)?(t.count+t.cloneOffset)*p:0}
else if(t.currentSlide===t.last&&n===0&&i.animationLoop&&t.direction!=='prev'){m=(r)?0:(t.count+1)*p}
else{m=(r)?((t.count-1)-n+t.cloneOffset)*p:(n+t.cloneOffset)*p};t.setProps(m,'',i.animationSpeed);if(t.transitions){if(!i.animationLoop||!t.atEnd){t.animating=!1;t.currentSlide=t.animatingTo};t.container.unbind('webkitTransitionEnd transitionend');t.container.bind('webkitTransitionEnd transitionend',function(){t.wrapup(p)})}
else{t.container.animate(t.args,i.animationSpeed,i.easing,function(){t.wrapup(p)})}}
else{if(!u){t.slides.eq(t.currentSlide).fadeOut(i.animationSpeed,i.easing);t.slides.eq(n).fadeIn(i.animationSpeed,i.easing,t.wrapup)}
else{t.slides.eq(t.currentSlide).css({'opacity':0,'zIndex':1});t.slides.eq(n).css({'opacity':1,'zIndex':2});t.slides.unbind('webkitTransitionEnd transitionend');t.slides.eq(t.currentSlide).bind('webkitTransitionEnd transitionend',function(){i.after(t)});t.animating=!1;t.currentSlide=t.animatingTo}};if(i.smoothHeight)o.smoothHeight(i.animationSpeed)}};t.wrapup=function(e){if(!c&&!s){if(t.currentSlide===0&&t.animatingTo===t.last&&i.animationLoop){t.setProps(e,'jumpEnd')}
else if(t.currentSlide===t.last&&t.animatingTo===0&&i.animationLoop){t.setProps(e,'jumpStart')}};t.animating=!1;t.currentSlide=t.animatingTo;i.after(t)};t.animateSlides=function(){if(!t.animating)t.flexAnimate(t.getTarget('next'))};t.pause=function(){clearInterval(t.animatedSlides);t.playing=!1;if(i.pausePlay)o.pausePlay.update('play');if(t.syncExists)o.sync('pause')};t.play=function(){t.animatedSlides=setInterval(t.animateSlides,i.slideshowSpeed);t.playing=!0;if(i.pausePlay)o.pausePlay.update('pause');if(t.syncExists)o.sync('play')};t.canAdvance=function(e,n){var a=(f)?t.pagingCount-1:t.last;return(n)?!0:(f&&t.currentItem===t.count-1&&e===0&&t.direction==='prev')?!0:(f&&t.currentItem===0&&e===t.pagingCount-1&&t.direction!=='next')?!1:(e===t.currentSlide&&!f)?!1:(i.animationLoop)?!0:(t.atEnd&&t.currentSlide===0&&e===a&&t.direction!=='next')?!1:(t.atEnd&&t.currentSlide===a&&e===0&&t.direction==='next')?!1:!0};t.getTarget=function(e){t.direction=e;if(e==='next'){return(t.currentSlide===t.last)?0:t.currentSlide+1}
else{return(t.currentSlide===0)?t.last:t.currentSlide-1}};t.setProps=function(e,n,a){var o=(function(){var a=(e)?e:((t.itemW+i.itemMargin)*t.move)*t.animatingTo,o=(function(){if(s){return(n==='setTouch')?e:(r&&t.animatingTo===t.last)?0:(r)?t.limit-(((t.itemW+i.itemMargin)*t.move)*t.animatingTo):(t.animatingTo===t.last)?t.limit:a}
else{switch(n){case'setTotal':return(r)?((t.count-1)-t.currentSlide+t.cloneOffset)*e:(t.currentSlide+t.cloneOffset)*e;case'setTouch':return(r)?e:e;case'jumpEnd':return(r)?e:t.count*e;case'jumpStart':return(r)?t.count*e:e;default:return e}}}());return(o*-1)+'px'}());if(t.transitions){o=(l)?'translate3d(0,'+o+',0)':'translate3d('+o+',0,0)';a=(a!==undefined)?(a/1000)+'s':'0s';t.container.css('-'+t.pfx+'-transition-duration',a)};t.args[t.prop]=o;if(t.transitions||a===undefined)t.container.css(t.args)};t.setup=function(n){if(!c){var d,f;if(n==='init'){t.viewport=e('<div class="'+a+'viewport"></div>').css({'overflow':'hidden','position':'relative'}).appendTo(t).append(t.container);t.cloneCount=0;t.cloneOffset=0;if(r){f=e.makeArray(t.slides).reverse();t.slides=e(f);t.container.empty().append(t.slides)}};if(i.animationLoop&&!s){t.cloneCount=2;t.cloneOffset=1;if(n!=='init')t.container.find('.clone').remove();t.container.append(t.slides.first().clone().addClass('clone')).prepend(t.slides.last().clone().addClass('clone'))};t.newSlides=e(i.selector,t);d=(r)?t.count-1-t.currentSlide+t.cloneOffset:t.currentSlide+t.cloneOffset;if(l&&!s){t.container.height((t.count+t.cloneCount)*200+'%').css('position','absolute').width('100%');setTimeout(function(){t.newSlides.css({'display':'block'});t.doMath();t.viewport.height(t.h);t.setProps(d*t.h,'init')},(n==='init')?100:0)}
else{t.container.width((t.count+t.cloneCount)*200+'%');t.setProps(d*t.computedW,'init');setTimeout(function(){t.doMath();t.newSlides.css({'width':t.computedW,'float':'left','display':'block'});if(i.smoothHeight)o.smoothHeight()},(n==='init')?100:0)}}
else{t.slides.css({'width':'100%','float':'left','marginRight':'-100%','position':'relative'});if(n==='init'){if(!u){t.slides.eq(t.currentSlide).fadeIn(i.animationSpeed,i.easing)}
else{t.slides.css({'opacity':0,'display':'block','webkitTransition':'opacity '+i.animationSpeed/1000+'s ease','zIndex':1}).eq(t.currentSlide).css({'opacity':1,'zIndex':2})}};if(i.smoothHeight)o.smoothHeight()};if(!s)t.slides.removeClass(a+'active-slide').eq(t.currentSlide).addClass(a+'active-slide')};t.doMath=function(){var o=t.slides.first(),e=i.itemMargin,n=i.minItems,a=i.maxItems;t.w=t.width();t.h=o.height();t.boxPadding=o.outerWidth()-o.width();if(s){t.itemT=i.itemWidth+e;t.minW=(n)?n*t.itemT:t.w;t.maxW=(a)?a*t.itemT:t.w;t.itemW=(t.minW>t.w)?(t.w-(e*n))/n:(t.maxW<t.w)?(t.w-(e*a))/a:(i.itemWidth>t.w)?t.w:i.itemWidth;t.visible=Math.floor(t.w/(t.itemW+e));t.move=(i.move>0&&i.move<t.visible)?i.move:t.visible;t.pagingCount=Math.ceil(((t.count-t.visible)/t.move)+1);t.last=t.pagingCount-1;t.limit=(t.pagingCount===1)?0:(i.itemWidth>t.w)?((t.itemW+(e*2))*t.count)-t.w-e:((t.itemW+e)*t.count)-t.w-e}
else{t.itemW=t.w;t.pagingCount=t.count;t.last=t.count-1};t.computedW=t.itemW-t.boxPadding};t.update=function(e,n){t.doMath();if(!s){if(e<t.currentSlide){t.currentSlide+=1}
else if(e<=t.currentSlide&&e!==0){t.currentSlide-=1};t.animatingTo=t.currentSlide};if(i.controlNav&&!t.manualControls){if((n==='add'&&!s)||t.pagingCount>t.controlNav.length){o.controlNav.update('add')}
else if((n==='remove'&&!s)||t.pagingCount<t.controlNav.length){if(s&&t.currentSlide>t.last){t.currentSlide-=1;t.animatingTo-=1};o.controlNav.update('remove',t.last)}};if(i.directionNav)o.directionNav.update()};t.addSlide=function(n,a){var o=e(n);t.count+=1;t.last=t.count-1;if(l&&r){(a!==undefined)?t.slides.eq(t.count-a).after(o):t.container.prepend(o)}
else{(a!==undefined)?t.slides.eq(a).before(o):t.container.append(o)};t.update(a,'add');t.slides=e(i.selector+':not(.clone)',t);t.setup();i.added(t)};t.removeSlide=function(n){var a=(isNaN(n))?t.slides.index(e(n)):n;t.count-=1;t.last=t.count-1;if(isNaN(n)){e(n,t.slides).remove()}
else{(l&&r)?t.slides.eq(t.last).remove():t.slides.eq(n).remove()};t.doMath();t.update(a,'remove');t.slides=e(i.selector+':not(.clone)',t);t.setup();i.removed(t)};o.init()};e.flexslider.defaults={namespace:'flex-',selector:'.slides > li',animation:'fade',easing:'swing',direction:'horizontal',reverse:!1,animationLoop:!0,smoothHeight:!1,startAt:0,slideshow:!0,slideshowSpeed:7000,animationSpeed:400,initDelay:0,randomize:!1,pauseOnAction:!0,pauseOnHover:!0,useCSS:!0,touch:!0,video:!1,controlNav:!1,directionNav:!0,prevText:'Previous',nextText:'Next',keyboard:!0,multipleKeyboard:!1,mousewheel:!1,pausePlay:!1,pauseText:'Pause',playText:'Play',controlsContainer:'',manualControls:'',sync:'',asNavFor:'',itemWidth:0,itemMargin:0,minItems:0,maxItems:0,move:0,start:function(){},before:function(){},after:function(){},end:function(){},added:function(){},removed:function(){}};e.fn.flexslider=function(t){if(t===undefined)t={};if(typeof t==='object'){return this.each(function(){var i=e(this),a=(t.selector)?t.selector:'.slides > li',n=i.find(a);if(n.length===1){n.fadeIn(400);if(t.start)t.start(i)}
else if(i.data('flexslider')==undefined){new e.flexslider(this,t)}})}
else{var i=e(this).data('flexslider');switch(t){case'play':i.play();break;case'pause':i.pause();break;case'next':i.flexAnimate(i.getTarget('next'),!0);break;case'prev':case'previous':i.flexAnimate(i.getTarget('prev'),!0);break;default:if(typeof t==='number')i.flexAnimate(t,!0)}}}})(jQuery);(function(e){Drupal.behaviors.flexslider_format={attach:function(t,i){e(function(){e('.field-flexslider-format.flexslider',t).flexslider({animation:'fade'});e('.std-slider',t).flexslider({animation:'fade',controlNav:!0,directionNav:!0})})}}})(jQuery);;
/* Source and licensing information for the above line(s) can be found at https://projektballast.dk/sites/all/modules/tabvn/flexslider_format/js/jquery.flexslider.js. */
;/*})'"*/
/* Source and licensing information for the line(s) below can be found at https://projektballast.dk/sites/all/modules/google_analytics/googleanalytics.js. */
(function(e){Drupal.googleanalytics={};e(document).ready(function(){e(document.body).bind("mousedown keyup touchstart",function(t){e(t.target).closest("a,area").each(function(){if(Drupal.googleanalytics.isInternal(this.href)){if(e(this).is(".colorbox")&&(Drupal.settings.googleanalytics.trackColorbox)){}
else if(Drupal.settings.googleanalytics.trackDownload&&Drupal.googleanalytics.isDownload(this.href)){ga("send",{"hitType":"event","eventCategory":"Downloads","eventAction":Drupal.googleanalytics.getDownloadExtension(this.href).toUpperCase(),"eventLabel":Drupal.googleanalytics.getPageUrl(this.href),"transport":"beacon"})}
else if(Drupal.googleanalytics.isInternalSpecial(this.href)){ga("send",{"hitType":"pageview","page":Drupal.googleanalytics.getPageUrl(this.href),"transport":"beacon"})}}
else{if(Drupal.settings.googleanalytics.trackMailto&&e(this).is("a[href^='mailto:'],area[href^='mailto:']")){ga("send",{"hitType":"event","eventCategory":"Mails","eventAction":"Click","eventLabel":this.href.substring(7),"transport":"beacon"})}
else if(Drupal.settings.googleanalytics.trackOutbound&&this.href.match(/^\w+:\/\//i)){if(Drupal.settings.googleanalytics.trackDomainMode!==2||(Drupal.settings.googleanalytics.trackDomainMode===2&&!Drupal.googleanalytics.isCrossDomain(this.hostname,Drupal.settings.googleanalytics.trackCrossDomains))){ga("send",{"hitType":"event","eventCategory":"Outbound links","eventAction":"Click","eventLabel":this.href,"transport":"beacon"})}}}})});if(Drupal.settings.googleanalytics.trackUrlFragments){window.onhashchange=function(){ga("send",{"hitType":"pageview","page":location.pathname+location.search+location.hash})}};if(Drupal.settings.googleanalytics.trackColorbox){e(document).bind("cbox_complete",function(){var t=e.colorbox.element().attr("href");if(t){ga("send",{"hitType":"pageview","page":Drupal.googleanalytics.getPageUrl(t)})}})}});Drupal.googleanalytics.isCrossDomain=function(t,a){if(!a){return!1}
else{return e.inArray(t,a)>-1?!0:!1}};Drupal.googleanalytics.isDownload=function(e){var t=new RegExp("\\.("+Drupal.settings.googleanalytics.trackDownloadExtensions+")([\?#].*)?$","i");return t.test(e)};Drupal.googleanalytics.isInternal=function(e){var t=new RegExp("^(https?):\/\/"+window.location.host,"i");return t.test(e)};Drupal.googleanalytics.isInternalSpecial=function(e){var t=new RegExp("(\/go\/.*)$","i");return t.test(e)};Drupal.googleanalytics.getPageUrl=function(e){var t=new RegExp("^(https?):\/\/"+window.location.host,"i");return e.replace(t,"")};Drupal.googleanalytics.getDownloadExtension=function(e){var a=new RegExp("\\.("+Drupal.settings.googleanalytics.trackDownloadExtensions+")([\?#].*)?$","i"),t=a.exec(e);return(t===null)?"":t[1]}})(jQuery);;
/* Source and licensing information for the above line(s) can be found at https://projektballast.dk/sites/all/modules/google_analytics/googleanalytics.js. */
;/*})'"*/
