/* Source and licensing information for the line(s) below can be found at https://projektballast.dk/misc/jquery-html-prefilter-3.5.0-backport.js. */
(function(t){var o=t.fn.jquery.split('.'),e=parseInt(o[0]),r=parseInt(o[1]);if((e>3)||(e===3&&r>=5)){return};var p=['a','abbr','address','article','aside','audio','b','bdi','bdo','blockquote','button','canvas','caption','cite','code','data','datalist','dd','del','details','dfn','div','dl','dt','em','fieldset','figcaption','figure','footer','form','h1','h2','h3','h4','h5','h6','header','hgroup','i','ins','kbd','label','legend','li','main','map','mark','menu','meter','nav','ol','optgroup','option','output','p','picture','pre','progress','q','rp','rt','ruby','s','samp','section','select','small','source','span','strong','sub','summary','sup','table','tbody','td','tfoot','th','thead','time','tr','u','ul','var','video'],i='('+p.join('|')+')',c='[\\x20\\t\\r\\n\\f]',s=new RegExp('<'+i+'\\/>','gi'),b=new RegExp('<'+i+'('+c+'[^>]*)\\/>','gi'),a;if(e<3){a=/<([\w:]+)/}
else if(r<4){a=/<([a-z][^\/\0>\x20\t\r\n\f]+)/i}
else{a=/<([a-z][^\/\0>\x20\t\r\n\f]*)/i};var f=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi;t.extend({htmlPrefilter:function(t){var i=(a.exec(t)||['',''])[1].toLowerCase();if((i==='option'||i==='optgroup')&&t.match(/<\/?select/i)){t=''};t=t.replace(s,'<$1></$1>');t=t.replace(b,'<$1$2></$1>');if((e===1&&r<12)||(e===2&&r<2)){var p=t.replace(f,'<$1></$2>');if(p!==t){var n={thead:[1,'<table>','</table>'],col:[2,'<table><colgroup>','</colgroup></table>'],tr:[2,'<table><tbody>','</tbody></table>'],td:[3,'<table><tbody><tr>','</tr></tbody></table>'],};n.tbody=n.tfoot=n.colgroup=n.caption=n.thead;n.th=n.td;var o=function(t){var e=n[i];if(e){t=e[1]+t+e[2]};return t},l=function(t){var e=window.document.implementation.createHTMLDocument('');e.body.innerHTML=t;return e.body?e.body.innerHTML:''},d=l(o(t)),u=l(o(p));if(u===''||d===''||(u!==d)){t=''}}};return t}});if((e===1&&r<12)||(e===2&&r<2)){var u=t.fn.html;t.fn.extend({html:function(e){if(typeof e==='string'){e=t.htmlPrefilter(e)};return u.apply(this,arguments.length?[e]:[])}});var n=/<|&#?\w+;/;if(e===1&&r<9){var d=t.clean;t.extend({'clean':function(e,i,o,l){for(var a=0,r;(r=e[a])!=null;a++){if(typeof r==='string'&&n.test(r)){e[a]=r=t.htmlPrefilter(r)}};return d.call(this,e,i,o,l)}})}
else{var l=t.buildFragment;t.extend({'buildFragment':function(e,i,o,d){var u=e.length;for(var a=0;a<u;a++){var r=e[a];if(r||r===0){if(t.type(r)!=='object'&&n.test(r)){e[a]=r=t.htmlPrefilter(r)}}};return l.call(this,e,i,o,d)}})}}})(jQuery);;
/* Source and licensing information for the above line(s) can be found at https://projektballast.dk/misc/jquery-html-prefilter-3.5.0-backport.js. */
;/*})'"*/
/* Source and licensing information for the line(s) below can be found at https://projektballast.dk/misc/jquery.once.js. */
(function(n){var e={},i=0;n.fn.once=function(r,o){if(typeof r!='string'){if(!(r in e)){e[r]=++i};if(!o){o=r};r='jquery-once-'+e[r]};var s=r+'-processed',t=this.not('.'+s).addClass(s);return n.isFunction(o)?t.each(o):t};n.fn.removeOnce=function(e,i){var r=e+'-processed',o=this.filter('.'+r).removeClass(r);return n.isFunction(i)?o.each(i):o}})(jQuery);;
/* Source and licensing information for the above line(s) can be found at https://projektballast.dk/misc/jquery.once.js. */
;/*})'"*/
/* Source and licensing information for the line(s) below can be found at https://projektballast.dk/misc/drupal.js. */
;var Drupal=Drupal||{'settings':{},'behaviors':{},'locale':{}};jQuery.noConflict();(function(t){var r=t.fn.init;t.fn.init=function(t,e,a){if(t&&typeof t==='string'){var n=t.indexOf('#');if(n>=0){var o=t.indexOf('<');if(o>n){throw'Syntax error, unrecognized expression: '+t}}};return r.call(this,t,e,a)};t.fn.init.prototype=r.prototype;if(t.ajaxPrefilter){t.ajaxPrefilter(function(t){if(t.crossDomain){t.contents.script=!1}})}
else if(t.httpData){var e=t.httpData;t.httpData=function(t,r,a){if(!r&&!Drupal.urlIsLocal(a.url)){var n=t.getResponseHeader('content-type')||'';if(n.indexOf('javascript')>=0){r='text'}};return e.call(this,t,r,a)};t.httpData.prototype=e.prototype};Drupal.attachBehaviors=function(e,r){e=e||document;r=r||Drupal.settings;t.each(Drupal.behaviors,function(){if(t.isFunction(this.attach)){this.attach(e,r)}})};Drupal.detachBehaviors=function(e,r,a){e=e||document;r=r||Drupal.settings;a=a||'unload';t.each(Drupal.behaviors,function(){if(t.isFunction(this.detach)){this.detach(e,r,a)}})};Drupal.checkPlain=function(t){var e,a,r={'&':'&amp;','\'':'&#39;','"':'&quot;','<':'&lt;','>':'&gt;'};t=String(t);for(e in r){if(r.hasOwnProperty(e)){a=new RegExp(e,'g');t=t.replace(a,r[e])}};return t};Drupal.formatString=function(t,e){for(var r in e){if(e.hasOwnProperty(r)){switch(r.charAt(0)){case'@':e[r]=Drupal.checkPlain(e[r]);break;case'!':break;default:e[r]=Drupal.theme('placeholder',e[r]);break}}};return Drupal.stringReplace(t,e,null)};Drupal.stringReplace=function(e,r,a){if(e.length===0){return e};if(!t.isArray(a)){a=[];for(var u in r){if(r.hasOwnProperty(u)){a.push(u)}};a.sort(function(t,e){return t.length-e.length})};if(a.length===0){return e};var l=a.pop(),o=e.split(l);if(a.length){for(var n=0;n<o.length;n++){o[n]=Drupal.stringReplace(o[n],r,a.slice(0))}};return o.join(r[l])};Drupal.t=function(t,r,e){e=e||{};e.context=e.context||'';if(Drupal.locale.strings&&Drupal.locale.strings[e.context]&&Drupal.locale.strings[e.context][t]){t=Drupal.locale.strings[e.context][t]};if(r){t=Drupal.formatString(t,r)};return t};Drupal.formatPlural=function(t,e,a,r,o){r=r||{};r['@count']=t;var n=Drupal.locale.pluralFormula?Drupal.locale.pluralFormula(r['@count']):((r['@count']==1)?0:1);if(n==0){return Drupal.t(e,r,o)}
else if(n==1){return Drupal.t(a,r,o)}
else{r['@count['+n+']']=r['@count'];delete r['@count'];return Drupal.t(a.replace('@count','@count['+n+']'),r,o)}};Drupal.absoluteUrl=function(t){var r=document.createElement('a');try{t=decodeURIComponent(t)}catch(e){};r.setAttribute('href',t);return r.cloneNode(!1).href};Drupal.urlIsLocal=function(t){var e=Drupal.absoluteUrl(t),n=location.protocol;if(n==='http:'&&e.indexOf('https:')===0){n='https:'};var r=n+'//'+location.host+Drupal.settings.basePath.slice(0,-1);try{e=decodeURIComponent(e)}catch(a){};try{r=decodeURIComponent(r)}catch(a){};return e===r||e.indexOf(r+'/')===0};Drupal.theme=function(t){var e=Array.prototype.slice.apply(arguments,[1]);return(Drupal.theme[t]||Drupal.theme.prototype[t]).apply(this,e)};Drupal.freezeHeight=function(){Drupal.unfreezeHeight();t('<div id="freeze-height"></div>').css({position:'absolute',top:'0px',left:'0px',width:'1px',height:t('body').css('height')}).appendTo('body')};Drupal.unfreezeHeight=function(){t('#freeze-height').remove()};Drupal.encodePath=function(t,e){e=e||location.href;return encodeURIComponent(t).replace(/%2F/g,'/')};Drupal.getSelection=function(t){if(typeof t.selectionStart!='number'&&document.selection){var e=document.selection.createRange(),r=e.duplicate();r.moveToElementText(t);r.setEndPoint('EndToEnd',e);var a=r.text.length-e.text.length,n=a+e.text.length;return{'start':a,'end':n}};return{'start':t.selectionStart,'end':t.selectionEnd}};Drupal.beforeUnloadCalled=!1;t(window).bind('beforeunload pagehide',function(){Drupal.beforeUnloadCalled=!0});Drupal.displayAjaxError=function(t){if(!Drupal.beforeUnloadCalled){alert(t)}};Drupal.ajaxError=function(e,r,a){var o,u,i,n,p,s;if(e.status){o='\n'+Drupal.t('An AJAX HTTP error occurred.')+'\n'+Drupal.t('HTTP Result Code: !status',{'!status':e.status})}
else{o='\n'+Drupal.t('An AJAX HTTP request terminated abnormally.')};o+='\n'+Drupal.t('Debugging information follows.');i='\n'+Drupal.t('Path: !uri',{'!uri':r});u='';try{u='\n'+Drupal.t('StatusText: !statusText',{'!statusText':t.trim(e.statusText)})}catch(l){};n='';try{n='\n'+Drupal.t('ResponseText: !responseText',{'!responseText':t.trim(e.responseText)})}catch(l){};n=n.replace(/<("[^"]*"|'[^']*'|[^'">])*>/gi,'');n=n.replace(/[\n]+\s+/g,'\n');p=e.status==0?('\n'+Drupal.t('ReadyState: !readyState',{'!readyState':e.readyState})):'';a=a?('\n'+Drupal.t('CustomMessage: !customMessage',{'!customMessage':a})):'';s=o+i+u+a+n+p;return s};t('html').addClass('js');document.cookie='has_js=1; path=/';t(function(){if(jQuery.support.positionFixed===undefined){var e=t('<div style="position:fixed; top:10px" />').appendTo(document.body);jQuery.support.positionFixed=e[0].offsetTop===10;e.remove()}});t(function(){Drupal.attachBehaviors(document,Drupal.settings)});Drupal.theme.prototype={placeholder:function(t){return'<em class="placeholder">'+Drupal.checkPlain(t)+'</em>'}}})(jQuery);;
/* Source and licensing information for the above line(s) can be found at https://projektballast.dk/misc/drupal.js. */
;/*})'"*/
